// src/lib/db-models.ts

/**
 * Defines the structure for a single reusable UI component.
 */
export interface Component {
  /** A unique ID generated by the LLM (e.g., 'header-4x9z'). */
  id: string;
  /** The name of the component (e.g., 'Header', 'LoginForm', or 'Button'). */
  name: string;
  /** The full React/JSX code string for this specific component. */
  code: string;
  /** The type of HTML element (e.g., 'div', 'form', 'button') for context. */
  elementType: string;
  /** Optional: Short description generated by the LLM for display/context. */
  description?: string;
  /** Timestamp of the last successful patch/update to this component. */
  lastUpdated: Date;
}

/**
 * Defines the structure for an entire Inkwell 2.0 Project.
 * This represents the single source of truth for the generated UI.
 */
export interface UIProject {
  /** Unique ID for the project (e.g., a short UUID or MongoDB ObjectId). */
  projectId: string;
  /** The title of the project (e.g., "Login Flow Prototype"). */
  title: string;
  /** The user's initial prompt that generated this UI. */
  initialPrompt: string;
  /** The full, current, concatenated code for the entire UI (for quick iframe rendering). */
  fullCode: string;
  /** An array holding all individual components, maintaining their structure/order. */
  components: Component[];
  /** A simple history log to track changes for F-8.0 (Undo/Redo). */
  history: {
    timestamp: Date;
    description: string;
    model: string;
    patchId: string;
  }[];
  /** Global status or settings for the project. */
  status: 'draft' | 'published';
  /** Timestamp of project creation. */
  createdAt: Date;
}